package fis.poo.cinemalayout.view;

import java.util.ArrayList;
import javax.swing.JButton;
import javax.swing.JToggleButton;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */


/**
 *
 * @author jordy
 */
public class SeatsSelection extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(SeatsSelection.class.getName());
    
    public JToggleButton[] seats(){
        JToggleButton[] jtb = {A1, A2, A3, A4, A5, A6, A7, A8, A9, A10, A11, A12,
        B1, B2, B3, B4, B5, B6, B7, B8, B9, B10, B11, B12, C1, C2, C3, C4, C5, C6, C7, C8, C9, C10, C11, C12,
        D1, D2, D3, D4, D5, D6, D7, D8, D9, D10, D11, D12, E1, E2, E3, E4, E5, E6, E7, E8, E9, E10, E11, E12,
        F1, F2, F3, F4, F5, F6, F7, F8, F9, F10, F11, F12};
        return jtb;
    }
    
    String[] bn = {"A1", "A2", "A3", "A4", "A5", "A6", "A7", "A8", "A9", "A10", "A11", "A12",
        "B1", "B2", "B3", "B4", "B5", "B6", "B7", "B8", "B9", "B10", "B11", "B12", "C1", "C2", "C3", "C4", "C5", 
        "C6", "C7", "C8", "C9", "C10", "C11", "C12", "D1", "D2", "D3", "D4", "D5", "D6", "D7", "D8", "D9", "D10", 
        "D11", "D12", "E1", "E2", "E3", "E4", "E5", "E6", "E7", "E8", "E9", "E10", "E11", "E12", "F1", "F2", "F3", 
        "F4", "F5", "F6", "F7", "F8", "F9", "F10", "F11", "F12"};
    
    /**
     * Creates new form seatsSelection
     */
    public SeatsSelection() {
        initComponents();
        for(int i=0; i<seats().length; i++){
            seats()[i].setName(bn[i]);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        displayMN = new javax.swing.JTextField();
        displayH1 = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel25 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        displayS = new javax.swing.JTextField();
        aceptB = new javax.swing.JButton();
        cancelB1 = new javax.swing.JButton();
        jLabel24 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        A1 = new javax.swing.JToggleButton();
        B1 = new javax.swing.JToggleButton();
        C1 = new javax.swing.JToggleButton();
        D1 = new javax.swing.JToggleButton();
        E1 = new javax.swing.JToggleButton();
        F1 = new javax.swing.JToggleButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        A2 = new javax.swing.JToggleButton();
        D2 = new javax.swing.JToggleButton();
        E2 = new javax.swing.JToggleButton();
        F2 = new javax.swing.JToggleButton();
        B2 = new javax.swing.JToggleButton();
        C2 = new javax.swing.JToggleButton();
        D3 = new javax.swing.JToggleButton();
        A3 = new javax.swing.JToggleButton();
        B3 = new javax.swing.JToggleButton();
        C3 = new javax.swing.JToggleButton();
        F3 = new javax.swing.JToggleButton();
        E3 = new javax.swing.JToggleButton();
        A4 = new javax.swing.JToggleButton();
        C4 = new javax.swing.JToggleButton();
        B4 = new javax.swing.JToggleButton();
        D4 = new javax.swing.JToggleButton();
        E4 = new javax.swing.JToggleButton();
        F4 = new javax.swing.JToggleButton();
        A5 = new javax.swing.JToggleButton();
        C5 = new javax.swing.JToggleButton();
        F5 = new javax.swing.JToggleButton();
        E5 = new javax.swing.JToggleButton();
        D5 = new javax.swing.JToggleButton();
        B5 = new javax.swing.JToggleButton();
        B6 = new javax.swing.JToggleButton();
        A6 = new javax.swing.JToggleButton();
        E6 = new javax.swing.JToggleButton();
        F6 = new javax.swing.JToggleButton();
        D6 = new javax.swing.JToggleButton();
        C6 = new javax.swing.JToggleButton();
        C7 = new javax.swing.JToggleButton();
        D7 = new javax.swing.JToggleButton();
        F7 = new javax.swing.JToggleButton();
        E7 = new javax.swing.JToggleButton();
        A7 = new javax.swing.JToggleButton();
        B7 = new javax.swing.JToggleButton();
        B8 = new javax.swing.JToggleButton();
        A8 = new javax.swing.JToggleButton();
        E8 = new javax.swing.JToggleButton();
        F8 = new javax.swing.JToggleButton();
        D8 = new javax.swing.JToggleButton();
        C8 = new javax.swing.JToggleButton();
        F9 = new javax.swing.JToggleButton();
        E9 = new javax.swing.JToggleButton();
        B9 = new javax.swing.JToggleButton();
        A9 = new javax.swing.JToggleButton();
        C9 = new javax.swing.JToggleButton();
        D9 = new javax.swing.JToggleButton();
        D10 = new javax.swing.JToggleButton();
        C10 = new javax.swing.JToggleButton();
        A10 = new javax.swing.JToggleButton();
        B10 = new javax.swing.JToggleButton();
        E10 = new javax.swing.JToggleButton();
        F10 = new javax.swing.JToggleButton();
        A11 = new javax.swing.JToggleButton();
        C11 = new javax.swing.JToggleButton();
        D11 = new javax.swing.JToggleButton();
        F11 = new javax.swing.JToggleButton();
        E11 = new javax.swing.JToggleButton();
        B11 = new javax.swing.JToggleButton();
        B12 = new javax.swing.JToggleButton();
        E12 = new javax.swing.JToggleButton();
        F12 = new javax.swing.JToggleButton();
        D12 = new javax.swing.JToggleButton();
        C12 = new javax.swing.JToggleButton();
        A12 = new javax.swing.JToggleButton();
        displayH = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(102, 0, 0));

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));

        displayMN.setEditable(false);
        displayMN.setBackground(new java.awt.Color(0, 0, 0));
        displayMN.setFont(new java.awt.Font("Perpetua", 2, 36)); // NOI18N
        displayMN.setForeground(new java.awt.Color(255, 255, 255));
        displayMN.setText("Movie Name");
        displayMN.setBorder(null);
        displayMN.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        displayMN.setFocusable(false);
        displayMN.setRequestFocusEnabled(false);
        displayMN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                displayMNActionPerformed(evt);
            }
        });

        displayH1.setEditable(false);
        displayH1.setBackground(new java.awt.Color(0, 0, 0));
        displayH1.setFont(new java.awt.Font("Perpetua", 2, 36)); // NOI18N
        displayH1.setForeground(new java.awt.Color(255, 255, 255));
        displayH1.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        displayH1.setText("Schedule");
        displayH1.setBorder(null);
        displayH1.setFocusable(false);
        displayH1.setRequestFocusEnabled(false);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(displayMN, javax.swing.GroupLayout.PREFERRED_SIZE, 374, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(displayH1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(displayMN, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE)
                    .addComponent(displayH1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0))
        );

        jPanel1.setBackground(new java.awt.Color(102, 0, 0));

        jLabel25.setFont(new java.awt.Font("Monotype Corsiva", 0, 24)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(255, 255, 255));
        jLabel25.setText("Seat Selection:");

        jPanel6.setBackground(new java.awt.Color(102, 0, 51));

        displayS.setEditable(false);
        displayS.setBackground(new java.awt.Color(255, 255, 255));
        displayS.setBorder(null);
        displayS.setDisabledTextColor(new java.awt.Color(255, 255, 255));

        aceptB.setText("Acept");

        cancelB1.setText("Cancel");

        jLabel24.setFont(new java.awt.Font("Perpetua", 2, 14)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(255, 255, 255));
        jLabel24.setText("Total Seats:");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(aceptB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel24)
                            .addComponent(displayS, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(cancelB1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(jLabel24)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(displayS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 108, Short.MAX_VALUE)
                .addComponent(aceptB)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cancelB1)
                .addGap(27, 27, 27))
        );

        jPanel5.setBackground(new java.awt.Color(0, 0, 0));

        A1.setBackground(new java.awt.Color(204, 0, 0));
        A1.setFont(new java.awt.Font("Times New Roman", 0, 8)); // NOI18N
        A1.setText("|");

        B1.setBackground(new java.awt.Color(204, 0, 0));
        B1.setFont(new java.awt.Font("Times New Roman", 0, 8)); // NOI18N
        B1.setText("|");

        C1.setBackground(new java.awt.Color(204, 0, 0));
        C1.setFont(new java.awt.Font("Times New Roman", 0, 8)); // NOI18N
        C1.setText("|");

        D1.setBackground(new java.awt.Color(204, 0, 0));
        D1.setFont(new java.awt.Font("Times New Roman", 0, 8)); // NOI18N
        D1.setText("|");

        E1.setBackground(new java.awt.Color(204, 0, 0));
        E1.setFont(new java.awt.Font("Times New Roman", 0, 8)); // NOI18N
        E1.setText("|");

        F1.setBackground(new java.awt.Color(204, 0, 0));
        F1.setFont(new java.awt.Font("Times New Roman", 0, 8)); // NOI18N
        F1.setText("|");

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("A");

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("C");

        jLabel8.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("B");

        jLabel9.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("E");

        jLabel10.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("D");

        jLabel11.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("F");

        jLabel12.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("2");

        jLabel13.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("1");

        jLabel14.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("3");

        jLabel15.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("4");

        jLabel16.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("5");
        jLabel16.setToolTipText("");

        jLabel17.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("6");
        jLabel17.setToolTipText("");

        jLabel18.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("7");
        jLabel18.setToolTipText("");

        jLabel19.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("8");
        jLabel19.setToolTipText("");

        jLabel20.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("9");
        jLabel20.setToolTipText("");

        jLabel21.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText("10");
        jLabel21.setToolTipText("");

        jLabel22.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setText("11");
        jLabel22.setToolTipText("");

        jLabel23.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(255, 255, 255));
        jLabel23.setText("12");
        jLabel23.setToolTipText("");

        A2.setBackground(new java.awt.Color(204, 0, 0));
        A2.setFont(new java.awt.Font("Times New Roman", 0, 8)); // NOI18N
        A2.setText("|");

        D2.setBackground(new java.awt.Color(204, 0, 0));
        D2.setFont(new java.awt.Font("Times New Roman", 0, 8)); // NOI18N
        D2.setText("|");

        E2.setBackground(new java.awt.Color(204, 0, 0));
        E2.setFont(new java.awt.Font("Times New Roman", 0, 8)); // NOI18N
        E2.setText("|");

        F2.setBackground(new java.awt.Color(204, 0, 0));
        F2.setFont(new java.awt.Font("Times New Roman", 0, 8)); // NOI18N
        F2.setText("|");

        B2.setBackground(new java.awt.Color(204, 0, 0));
        B2.setFont(new java.awt.Font("Times New Roman", 0, 8)); // NOI18N
        B2.setText("|");

        C2.setBackground(new java.awt.Color(204, 0, 0));
        C2.setFont(new java.awt.Font("Times New Roman", 0, 8)); // NOI18N
        C2.setText("|");

        D3.setBackground(new java.awt.Color(204, 0, 0));
        D3.setFont(new java.awt.Font("Times New Roman", 0, 8)); // NOI18N
        D3.setText("|");

        A3.setBackground(new java.awt.Color(204, 0, 0));
        A3.setFont(new java.awt.Font("Times New Roman", 0, 8)); // NOI18N
        A3.setText("|");

        B3.setBackground(new java.awt.Color(204, 0, 0));
        B3.setFont(new java.awt.Font("Times New Roman", 0, 8)); // NOI18N
        B3.setText("|");

        C3.setBackground(new java.awt.Color(204, 0, 0));
        C3.setFont(new java.awt.Font("Times New Roman", 0, 8)); // NOI18N
        C3.setText("|");

        F3.setBackground(new java.awt.Color(204, 0, 0));
        F3.setFont(new java.awt.Font("Times New Roman", 0, 8)); // NOI18N
        F3.setText("|");

        E3.setBackground(new java.awt.Color(204, 0, 0));
        E3.setFont(new java.awt.Font("Times New Roman", 0, 8)); // NOI18N
        E3.setText("|");

        A4.setBackground(new java.awt.Color(204, 0, 0));
        A4.setFont(new java.awt.Font("Times New Roman", 0, 8)); // NOI18N
        A4.setText("|");

        C4.setBackground(new java.awt.Color(204, 0, 0));
        C4.setFont(new java.awt.Font("Times New Roman", 0, 8)); // NOI18N
        C4.setText("|");

        B4.setBackground(new java.awt.Color(204, 0, 0));
        B4.setFont(new java.awt.Font("Times New Roman", 0, 8)); // NOI18N
        B4.setText("|");

        D4.setBackground(new java.awt.Color(204, 0, 0));
        D4.setFont(new java.awt.Font("Times New Roman", 0, 8)); // NOI18N
        D4.setText("|");

        E4.setBackground(new java.awt.Color(204, 0, 0));
        E4.setFont(new java.awt.Font("Times New Roman", 0, 8)); // NOI18N
        E4.setText("|");

        F4.setBackground(new java.awt.Color(204, 0, 0));
        F4.setFont(new java.awt.Font("Times New Roman", 0, 8)); // NOI18N
        F4.setText("|");

        A5.setBackground(new java.awt.Color(204, 0, 0));
        A5.setFont(new java.awt.Font("Times New Roman", 0, 8)); // NOI18N
        A5.setText("|");

        C5.setBackground(new java.awt.Color(204, 0, 0));
        C5.setFont(new java.awt.Font("Times New Roman", 0, 8)); // NOI18N
        C5.setText("|");

        F5.setBackground(new java.awt.Color(204, 0, 0));
        F5.setFont(new java.awt.Font("Times New Roman", 0, 8)); // NOI18N
        F5.setText("|");

        E5.setBackground(new java.awt.Color(204, 0, 0));
        E5.setFont(new java.awt.Font("Times New Roman", 0, 8)); // NOI18N
        E5.setText("|");

        D5.setBackground(new java.awt.Color(204, 0, 0));
        D5.setFont(new java.awt.Font("Times New Roman", 0, 8)); // NOI18N
        D5.setText("|");

        B5.setBackground(new java.awt.Color(204, 0, 0));
        B5.setFont(new java.awt.Font("Times New Roman", 0, 8)); // NOI18N
        B5.setText("|");

        B6.setBackground(new java.awt.Color(204, 0, 0));
        B6.setFont(new java.awt.Font("Times New Roman", 0, 8)); // NOI18N
        B6.setText("|");

        A6.setBackground(new java.awt.Color(204, 0, 0));
        A6.setFont(new java.awt.Font("Times New Roman", 0, 8)); // NOI18N
        A6.setText("|");

        E6.setBackground(new java.awt.Color(204, 0, 0));
        E6.setFont(new java.awt.Font("Times New Roman", 0, 8)); // NOI18N
        E6.setText("|");

        F6.setBackground(new java.awt.Color(204, 0, 0));
        F6.setFont(new java.awt.Font("Times New Roman", 0, 8)); // NOI18N
        F6.setText("|");

        D6.setBackground(new java.awt.Color(204, 0, 0));
        D6.setFont(new java.awt.Font("Times New Roman", 0, 8)); // NOI18N
        D6.setText("|");

        C6.setBackground(new java.awt.Color(204, 0, 0));
        C6.setFont(new java.awt.Font("Times New Roman", 0, 8)); // NOI18N
        C6.setText("|");

        C7.setBackground(new java.awt.Color(204, 0, 0));
        C7.setFont(new java.awt.Font("Times New Roman", 0, 8)); // NOI18N
        C7.setText("|");

        D7.setBackground(new java.awt.Color(204, 0, 0));
        D7.setFont(new java.awt.Font("Times New Roman", 0, 8)); // NOI18N
        D7.setText("|");

        F7.setBackground(new java.awt.Color(204, 0, 0));
        F7.setFont(new java.awt.Font("Times New Roman", 0, 8)); // NOI18N
        F7.setText("|");

        E7.setBackground(new java.awt.Color(204, 0, 0));
        E7.setFont(new java.awt.Font("Times New Roman", 0, 8)); // NOI18N
        E7.setText("|");

        A7.setBackground(new java.awt.Color(204, 0, 0));
        A7.setFont(new java.awt.Font("Times New Roman", 0, 8)); // NOI18N
        A7.setText("|");

        B7.setBackground(new java.awt.Color(204, 0, 0));
        B7.setFont(new java.awt.Font("Times New Roman", 0, 8)); // NOI18N
        B7.setText("|");

        B8.setBackground(new java.awt.Color(204, 0, 0));
        B8.setFont(new java.awt.Font("Times New Roman", 0, 8)); // NOI18N
        B8.setText("|");

        A8.setBackground(new java.awt.Color(204, 0, 0));
        A8.setFont(new java.awt.Font("Times New Roman", 0, 8)); // NOI18N
        A8.setText("|");

        E8.setBackground(new java.awt.Color(204, 0, 0));
        E8.setFont(new java.awt.Font("Times New Roman", 0, 8)); // NOI18N
        E8.setText("|");

        F8.setBackground(new java.awt.Color(204, 0, 0));
        F8.setFont(new java.awt.Font("Times New Roman", 0, 8)); // NOI18N
        F8.setText("|");

        D8.setBackground(new java.awt.Color(204, 0, 0));
        D8.setFont(new java.awt.Font("Times New Roman", 0, 8)); // NOI18N
        D8.setText("|");

        C8.setBackground(new java.awt.Color(204, 0, 0));
        C8.setFont(new java.awt.Font("Times New Roman", 0, 8)); // NOI18N
        C8.setText("|");

        F9.setBackground(new java.awt.Color(204, 0, 0));
        F9.setFont(new java.awt.Font("Times New Roman", 0, 8)); // NOI18N
        F9.setText("|");

        E9.setBackground(new java.awt.Color(204, 0, 0));
        E9.setFont(new java.awt.Font("Times New Roman", 0, 8)); // NOI18N
        E9.setText("|");

        B9.setBackground(new java.awt.Color(204, 0, 0));
        B9.setFont(new java.awt.Font("Times New Roman", 0, 8)); // NOI18N
        B9.setText("|");

        A9.setBackground(new java.awt.Color(204, 0, 0));
        A9.setFont(new java.awt.Font("Times New Roman", 0, 8)); // NOI18N
        A9.setText("|");

        C9.setBackground(new java.awt.Color(204, 0, 0));
        C9.setFont(new java.awt.Font("Times New Roman", 0, 8)); // NOI18N
        C9.setText("|");

        D9.setBackground(new java.awt.Color(204, 0, 0));
        D9.setFont(new java.awt.Font("Times New Roman", 0, 8)); // NOI18N
        D9.setText("|");

        D10.setBackground(new java.awt.Color(204, 0, 0));
        D10.setFont(new java.awt.Font("Times New Roman", 0, 8)); // NOI18N
        D10.setText("|");

        C10.setBackground(new java.awt.Color(204, 0, 0));
        C10.setFont(new java.awt.Font("Times New Roman", 0, 8)); // NOI18N
        C10.setText("|");

        A10.setBackground(new java.awt.Color(204, 0, 0));
        A10.setFont(new java.awt.Font("Times New Roman", 0, 8)); // NOI18N
        A10.setText("|");

        B10.setBackground(new java.awt.Color(204, 0, 0));
        B10.setFont(new java.awt.Font("Times New Roman", 0, 8)); // NOI18N
        B10.setText("|");

        E10.setBackground(new java.awt.Color(204, 0, 0));
        E10.setFont(new java.awt.Font("Times New Roman", 0, 8)); // NOI18N
        E10.setText("|");

        F10.setBackground(new java.awt.Color(204, 0, 0));
        F10.setFont(new java.awt.Font("Times New Roman", 0, 8)); // NOI18N
        F10.setText("|");

        A11.setBackground(new java.awt.Color(204, 0, 0));
        A11.setFont(new java.awt.Font("Times New Roman", 0, 8)); // NOI18N
        A11.setText("|");

        C11.setBackground(new java.awt.Color(204, 0, 0));
        C11.setFont(new java.awt.Font("Times New Roman", 0, 8)); // NOI18N
        C11.setText("|");

        D11.setBackground(new java.awt.Color(204, 0, 0));
        D11.setFont(new java.awt.Font("Times New Roman", 0, 8)); // NOI18N
        D11.setText("|");

        F11.setBackground(new java.awt.Color(204, 0, 0));
        F11.setFont(new java.awt.Font("Times New Roman", 0, 8)); // NOI18N
        F11.setText("|");

        E11.setBackground(new java.awt.Color(204, 0, 0));
        E11.setFont(new java.awt.Font("Times New Roman", 0, 8)); // NOI18N
        E11.setText("|");

        B11.setBackground(new java.awt.Color(204, 0, 0));
        B11.setFont(new java.awt.Font("Times New Roman", 0, 8)); // NOI18N
        B11.setText("|");

        B12.setBackground(new java.awt.Color(204, 0, 0));
        B12.setFont(new java.awt.Font("Times New Roman", 0, 8)); // NOI18N
        B12.setText("|");

        E12.setBackground(new java.awt.Color(204, 0, 0));
        E12.setFont(new java.awt.Font("Times New Roman", 0, 8)); // NOI18N
        E12.setText("|");

        F12.setBackground(new java.awt.Color(204, 0, 0));
        F12.setFont(new java.awt.Font("Times New Roman", 0, 8)); // NOI18N
        F12.setText("|");

        D12.setBackground(new java.awt.Color(204, 0, 0));
        D12.setFont(new java.awt.Font("Times New Roman", 0, 8)); // NOI18N
        D12.setText("|");

        C12.setBackground(new java.awt.Color(204, 0, 0));
        C12.setFont(new java.awt.Font("Times New Roman", 0, 8)); // NOI18N
        C12.setText("|");

        A12.setBackground(new java.awt.Color(204, 0, 0));
        A12.setFont(new java.awt.Font("Times New Roman", 0, 8)); // NOI18N
        A12.setText("|");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(F1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(E1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(D1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(C1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(B1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(A1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(F2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(E2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(D2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(C2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(B2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(A2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(6, 6, 6)))
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel15)
                        .addGap(26, 26, 26)
                        .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel22)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel23)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(F3, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(E3, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(D3, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(C3, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(B3, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(A3, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(F4, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(E4, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(D4, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(C4, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(B4, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(A4, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(F5, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(E5, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(D5, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(C5, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(B5, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(A5, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(F6, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(E6, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(D6, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(C6, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(B6, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(A6, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(F7, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(E7, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(D7, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(C7, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(B7, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(A7, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(F8, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(E8, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(D8, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(C8, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(B8, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(A8, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(F9, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(E9, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(D9, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(C9, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(B9, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(A9, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(F10, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(E10, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(D10, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(C10, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(B10, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(A10, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(F11, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(E11, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(D11, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(C11, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(B11, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(A11, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(F12, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(E12, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(D12, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(C12, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(B12, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(A12, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 22, Short.MAX_VALUE))))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(jLabel13)
                            .addComponent(jLabel14)
                            .addComponent(jLabel15)
                            .addComponent(jLabel16)
                            .addComponent(jLabel17)
                            .addComponent(jLabel18)
                            .addComponent(jLabel19)
                            .addComponent(jLabel20)
                            .addComponent(jLabel21)
                            .addComponent(jLabel22)
                            .addComponent(jLabel23))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel5Layout.createSequentialGroup()
                                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(A1)
                                            .addComponent(jLabel3))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(B1)
                                            .addComponent(jLabel8))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(C1)
                                            .addComponent(jLabel4))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(D1)
                                            .addComponent(jLabel10))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(E1)
                                            .addComponent(jLabel9))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(F1)
                                            .addComponent(jLabel11)))
                                    .addGroup(jPanel5Layout.createSequentialGroup()
                                        .addComponent(A2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(B2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(C2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(D2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(E2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(F2))
                                    .addGroup(jPanel5Layout.createSequentialGroup()
                                        .addComponent(A3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(B3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(C3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(D3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(E3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(F3))
                                    .addGroup(jPanel5Layout.createSequentialGroup()
                                        .addComponent(A4)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(B4)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(C4)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(D4)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(E4)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(F4))
                                    .addGroup(jPanel5Layout.createSequentialGroup()
                                        .addComponent(A5)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(B5)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(C5)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(D5)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(E5)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(F5))
                                    .addGroup(jPanel5Layout.createSequentialGroup()
                                        .addComponent(A6)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(B6)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(C6)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(D6)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(E6)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(F6))
                                    .addGroup(jPanel5Layout.createSequentialGroup()
                                        .addComponent(A7)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(B7)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(C7)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(D7)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(E7)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(F7))
                                    .addGroup(jPanel5Layout.createSequentialGroup()
                                        .addComponent(A8)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(B8)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(C8)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(D8)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(E8)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(F8)))
                                .addGroup(jPanel5Layout.createSequentialGroup()
                                    .addComponent(A9)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(B9)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(C9)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(D9)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(E9)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(F9)))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(A10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(B10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(C10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(D10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(E10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(F10))))
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel5Layout.createSequentialGroup()
                            .addComponent(A12)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(B12)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(C12)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(D12)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(E12)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(F12))
                        .addGroup(jPanel5Layout.createSequentialGroup()
                            .addComponent(A11)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(B11)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(C11)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(D11)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(E11)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(F11))))
                .addContainerGap(29, Short.MAX_VALUE))
        );

        displayH.setEditable(false);
        displayH.setBackground(new java.awt.Color(102, 0, 0));
        displayH.setFont(new java.awt.Font("Perpetua", 2, 24)); // NOI18N
        displayH.setForeground(new java.awt.Color(255, 255, 255));
        displayH.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        displayH.setText("Hall");
        displayH.setBorder(null);
        displayH.setFocusable(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(displayH, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(displayH, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(41, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void displayMNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_displayMNActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_displayMNActionPerformed

    /**
     * @param args the command line arguments
     */
    
    public void clear(){
        displayS.setText("");
    }
    public void show(int a){
        displayS.setText(Integer.toString(a));
    }
    
    public String buttonPostion(JToggleButton jtg){
        return jtg.getName();
    }
        
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new SeatsSelection().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JToggleButton A1;
    public javax.swing.JToggleButton A10;
    public javax.swing.JToggleButton A11;
    public javax.swing.JToggleButton A12;
    public javax.swing.JToggleButton A2;
    public javax.swing.JToggleButton A3;
    public javax.swing.JToggleButton A4;
    public javax.swing.JToggleButton A5;
    public javax.swing.JToggleButton A6;
    public javax.swing.JToggleButton A7;
    public javax.swing.JToggleButton A8;
    public javax.swing.JToggleButton A9;
    public javax.swing.JToggleButton B1;
    public javax.swing.JToggleButton B10;
    public javax.swing.JToggleButton B11;
    public javax.swing.JToggleButton B12;
    public javax.swing.JToggleButton B2;
    public javax.swing.JToggleButton B3;
    public javax.swing.JToggleButton B4;
    public javax.swing.JToggleButton B5;
    public javax.swing.JToggleButton B6;
    public javax.swing.JToggleButton B7;
    public javax.swing.JToggleButton B8;
    public javax.swing.JToggleButton B9;
    public javax.swing.JToggleButton C1;
    public javax.swing.JToggleButton C10;
    public javax.swing.JToggleButton C11;
    public javax.swing.JToggleButton C12;
    public javax.swing.JToggleButton C2;
    public javax.swing.JToggleButton C3;
    public javax.swing.JToggleButton C4;
    public javax.swing.JToggleButton C5;
    public javax.swing.JToggleButton C6;
    public javax.swing.JToggleButton C7;
    public javax.swing.JToggleButton C8;
    public javax.swing.JToggleButton C9;
    public javax.swing.JToggleButton D1;
    public javax.swing.JToggleButton D10;
    public javax.swing.JToggleButton D11;
    public javax.swing.JToggleButton D12;
    public javax.swing.JToggleButton D2;
    public javax.swing.JToggleButton D3;
    public javax.swing.JToggleButton D4;
    public javax.swing.JToggleButton D5;
    public javax.swing.JToggleButton D6;
    public javax.swing.JToggleButton D7;
    public javax.swing.JToggleButton D8;
    public javax.swing.JToggleButton D9;
    public javax.swing.JToggleButton E1;
    public javax.swing.JToggleButton E10;
    public javax.swing.JToggleButton E11;
    public javax.swing.JToggleButton E12;
    public javax.swing.JToggleButton E2;
    public javax.swing.JToggleButton E3;
    public javax.swing.JToggleButton E4;
    public javax.swing.JToggleButton E5;
    public javax.swing.JToggleButton E6;
    public javax.swing.JToggleButton E7;
    public javax.swing.JToggleButton E8;
    public javax.swing.JToggleButton E9;
    public javax.swing.JToggleButton F1;
    public javax.swing.JToggleButton F10;
    public javax.swing.JToggleButton F11;
    public javax.swing.JToggleButton F12;
    public javax.swing.JToggleButton F2;
    public javax.swing.JToggleButton F3;
    public javax.swing.JToggleButton F4;
    public javax.swing.JToggleButton F5;
    public javax.swing.JToggleButton F6;
    public javax.swing.JToggleButton F7;
    public javax.swing.JToggleButton F8;
    public javax.swing.JToggleButton F9;
    public javax.swing.JButton aceptB;
    public javax.swing.JButton cancelB1;
    public javax.swing.JTextField displayH;
    public javax.swing.JTextField displayH1;
    public javax.swing.JTextField displayMN;
    public javax.swing.JTextField displayS;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    // End of variables declaration//GEN-END:variables
}
